[package]
name = "server"
version = "0.1.0"
authors = ["kevin <me@kvnvelasco.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
librsync-ffi = { path = "/media/kevin/Data/Projects/librsync-rust"}
rocket = "0.4.4"